### ISSUE TITLE
Pokebuddy doesnt start

### ISSUE THREAD

**Issue by hzni** [finndev/PokeBuddy#51]
The programm doesnt sart on my Pc. What I can do to fix it?

**Comment by Vanethir** [comment]
Any error message you get? 
Probably the programm is blocked by your antivirus programm?  Had issues with realtime scanner deleting the PokeBuddy Executable myself.

**Comment by brijei** [comment]
download a clean copy from github. extract pokebuddy.zip inside the master and click yes to all. should be fixed now.

**Comment by shahmanav97** [comment]
@brijei  I download master and extracted pokebuddy.zip in master. It still does not start. Cant start through Compactibility mode too. Cant you connect through team viewer please?
